import React, { useState } from 'react'
import { Check, HelpCircle, Search, ShieldAlert, X } from 'lucide-react'
import { api } from '../services/api'
import * as Types from '../types'

export default function Investigation({ competitor }: { competitor: string }) {
  const [hypothesis,setHypothesis]=useState('ApexAI is moving toward enterprise'); const [result,setResult]=useState<Types.Investigation|null>(null); const [gaps,setGaps]=useState<string[]>([]); const [loading,setLoading]=useState(false)
  async function run(mode:'investigate'|'prove'|'disprove'='investigate'){if(!hypothesis.trim())return;setLoading(true);try{const r=mode==='prove'?await api.proveHypothesis(hypothesis,competitor):mode==='disprove'?await api.disproveHypothesis(hypothesis,competitor):await api.investigate(hypothesis,competitor);const g=await api.identifyGaps(competitor);if(mode==='investigate')setResult(r);else if(mode==='prove')setResult({...result,hypothesis,supporting_evidence:r.evidence||[],contradicting_evidence:result?.contradicting_evidence||[],unknowns:result?.unknowns||g.gaps||[],confidence:result?.confidence||0,strength:'Evidence found'}) ; else setResult({...result,hypothesis,supporting_evidence:result?.supporting_evidence||[],contradicting_evidence:r.contradicting_evidence||[],unknowns:result?.unknowns||g.gaps||[],confidence:result?.confidence||0,strength:'Contradicting evidence found'});setGaps(g.gaps||[])}catch(e){console.error(e)}finally{setLoading(false)}}
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-violet-50 p-2.5 text-violet-600"><Search size={21}/></span><div><h2 className="text-xl font-bold text-slate-900">Competitive detective</h2><p className="text-sm text-slate-500">Test a hypothesis against observed evidence instead of accepting an AI guess.</p></div></div><div className="mt-5 flex flex-col gap-3 md:flex-row"><input value={hypothesis} onChange={e=>setHypothesis(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} className="flex-1 rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" placeholder="e.g. Competitor is moving toward enterprise"/><button onClick={()=>run('investigate')} disabled={loading} className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white hover:bg-blue-700 disabled:opacity-50">{loading?'Working…':'Investigate'}</button></div></section>
  {result&&<><div className="flex flex-wrap gap-2"><button onClick={()=>run('prove')} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Prove it</button><button onClick={()=>run('disprove')} className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Disprove it</button></div><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Hypothesis</p><p className="mt-1 font-semibold text-slate-900">{result.hypothesis}</p></div><span className="text-3xl font-black text-blue-600">{(result.confidence*100).toFixed(0)}%</span></div><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{width:`${result.confidence*100}%`}}/></div><p className="mt-2 text-sm text-slate-500">{result.strength}</p></section>
  <Evidence title="Supporting evidence" icon={<Check size={18}/>} items={result.supporting_evidence} tone="green"/><Evidence title="Contradicting evidence" icon={<X size={18}/>} items={result.contradicting_evidence} tone="red"/><section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h3 className="flex items-center gap-2 font-bold text-amber-900"><HelpCircle size={18}/> What we do not know</h3><ul className="mt-3 space-y-2 text-sm text-amber-900">{(result.unknowns.length?result.unknowns:gaps).map((g,i)=><li key={i}>• {g}</li>)}</ul></section></>}
  </div>
}
function Evidence({title,icon,items,tone}:{title:string,icon:React.ReactNode,items:Types.Evidence[],tone:'green'|'red'}){const c=tone==='green'?['border-emerald-200','bg-emerald-50','text-emerald-800']:['border-red-200','bg-red-50','text-red-800'];return <section className={`rounded-2xl border ${c[0]} ${c[1]} p-6`}><h3 className={`flex items-center gap-2 font-bold ${c[2]}`}>{icon}{title} ({items.length})</h3>{items.length?<div className="mt-4 space-y-3">{items.slice(0,5).map((e,i)=><div key={i} className="rounded-xl border border-white bg-white p-4"><p className="font-semibold text-slate-900">{e.event_title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{e.explanation}</p><p className="mt-2 text-xs font-medium text-slate-400">{new Date(e.date).toLocaleDateString()}</p></div>)}</div>:<p className="mt-3 text-sm text-slate-600">No matching evidence was found.</p>}</section>}
