import React, { useEffect, useState } from 'react'
import { Brain, Database, Search } from 'lucide-react'
import { api } from '../services/api'

export default function MemoryExplorer({ competitor }: { competitor: string }) {
  const [memories,setMemories]=useState<any[]>([]); const [status,setStatus]=useState<any>(null); const [query,setQuery]=useState('pricing and enterprise strategy'); const [loading,setLoading]=useState(false)
  useEffect(()=>{load()},[competitor])
  async function load(){setLoading(true);try{const [m,s]=await Promise.all([api.getAllMemories(competitor),api.getMemoryStatus()]);setMemories(m.memories||[]);setStatus(s)}catch(e){console.error(e)}finally{setLoading(false)}}
  async function recall(){setLoading(true);try{const r=await api.recallMemory(query,competitor);setMemories(r.memories||[])}catch(e){console.error(e)}finally{setLoading(false)}}
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><Brain size={22}/></span><div><h2 className="text-xl font-bold text-slate-900">Hindsight Memory Explorer</h2><p className="text-sm text-slate-500">See the memories behind the analysis. The badge tells you whether this is real Hindsight or demo fallback.</p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${status?.connected?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{status?.mode||'Loading'}</span><span className="text-sm font-semibold text-slate-600">{memories.length} memories</span></div></div><div className="mt-5 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&recall()} className="w-full rounded-xl border border-slate-300 py-3 pl-10 pr-4 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" placeholder="Recall something from memory…"/></div><button onClick={recall} className="rounded-xl bg-slate-900 px-5 py-3 font-bold text-white hover:bg-slate-800">Recall</button></div></section>{loading?<div className="rounded-2xl bg-white p-10 text-center text-slate-500">Querying memory…</div>:<div className="grid gap-3">{memories.slice(0,30).map((m,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-4"><span className="rounded-xl bg-slate-100 p-2 text-slate-600"><Database size={18}/></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="font-semibold text-slate-900">{m.title||m.text||m.id||'Competitive memory'}</p><span className="text-xs text-slate-400">{m.date||m.timestamp?new Date(m.date||m.timestamp).toLocaleDateString():''}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{m.description||m.text||m.content||m.event_type||'Stored competitive context'}</p><div className="mt-3 flex flex-wrap gap-2">{m.competitor&&<span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">{m.competitor}</span>}{m.memory_type&&<span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{m.memory_type}</span>}</div></div></div></div>)}</div>}</div>
}
