import React, { useState } from 'react'
import { BrainCircuit, MessageCircle, Search } from 'lucide-react'
import { api } from '../services/api'

export default function MemoryAssistant({ competitor }: { competitor: string }) {
  const [question,setQuestion]=useState('What changed?'); const [answer,setAnswer]=useState<any>(null); const [loading,setLoading]=useState(false)
  const prompts=['What changed?','Have we seen this before?','What are we missing?','What happened last time?']
  async function ask(q=question){setQuestion(q); if(!q.trim()) return; q = `${competitor}: ${q}`;setLoading(true);try{setAnswer(await api.demoQuery(q))}catch(e){console.error(e)}finally{setLoading(false)}}
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><BrainCircuit size={22}/></span><div><h2 className="text-xl font-bold text-slate-900">Ask Competitive Memory</h2><p className="text-sm text-slate-500">Ask questions that require historical context, not just the latest event.</p></div></div><div className="mt-5 flex flex-wrap gap-2">{prompts.map(p=><button key={p} onClick={()=>ask(p)} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-blue-50 hover:text-blue-700">{p}</button>)}</div><div className="mt-4 flex gap-3"><div className="relative flex-1"><MessageCircle className="absolute left-3 top-3 text-slate-400" size={18}/><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} className="w-full rounded-xl border border-slate-300 py-3 pl-10 pr-4 outline-none focus:border-blue-500" placeholder="Ask the memory…"/></div><button onClick={()=>ask()} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-700"><Search size={18}/></button></div></section>{answer&&<section className="rounded-2xl border border-blue-100 bg-blue-50 p-6"><p className="text-xs font-bold uppercase tracking-wide text-blue-600">Memory response</p><h3 className="mt-2 text-lg font-bold text-slate-900">{answer.answer}</h3>{answer.strategy_shifts?.length>0&&<div className="mt-4 space-y-2">{answer.strategy_shifts.map((s:any,i:number)=><div key={i} className="rounded-xl bg-white p-4"><b>{s.from_strategy} → {s.to_strategy}</b><p className="mt-1 text-sm text-slate-600">{s.explanation}</p></div>)}</div>}{answer.historical_matches?.length>0&&<div className="mt-4"><p className="font-semibold text-slate-800">Historical matches</p><div className="mt-2 grid gap-2">{answer.historical_matches.map((e:any,i:number)=><div key={i} className="rounded-xl bg-white p-4 text-sm"><b>{e.title}</b><p className="mt-1 text-slate-600">{e.description}</p></div>)}</div></div>}{answer.unknowns?.length>0&&<ul className="mt-4 space-y-2 text-sm text-slate-700">{answer.unknowns.map((x:string,i:number)=><li key={i}>• {x}</li>)}</ul>}{loading&&<p className="mt-3 text-sm text-slate-500">Thinking…</p>}</section>}</div>
}
