import React, { useEffect, useState } from 'react'
import { Brain, Flag, Lightbulb, TrendingUp } from 'lucide-react'
import { api } from '../services/api'
import * as Types from '../types'

export default function Strategy({ competitor }: { competitor: string }) {
  const [profile,setProfile]=useState<Types.StrategyProfile|null>(null); const [shifts,setShifts]=useState<Types.StrategyShift[]>([]); const [first,setFirst]=useState<Types.CompetitorEvent|null>(null); const [patterns,setPatterns]=useState<Types.Pattern[]>([]); const [loading,setLoading]=useState(true)
  useEffect(()=>{load()},[competitor])
  async function load(){setLoading(true);try{const [s,f,p]=await Promise.all([api.getStrategy(competitor),api.getFirstSignal(competitor,'enterprise'),api.getPatterns(competitor)]);setProfile(s.current_profile);setShifts(s.strategy_shifts||[]);setFirst(f.first_signal);setPatterns(p.patterns||[])}catch(e){console.error(e)}finally{setLoading(false)}}
  if(loading)return <Loading/>; if(!profile)return <Empty/>
  return <div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><Brain size={22}/></span><div><h2 className="text-xl font-bold text-slate-900">Current strategy profile</h2><p className="text-sm text-slate-500">A structured read of the signals retained in the competitive history.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Primary strategy" value={profile.primary_strategy} tone="blue"/><Metric label="Confidence" value={`${(profile.confidence*100).toFixed(0)}%`} tone="violet"/><Metric label="Target customer" value={profile.target_customer} tone="cyan"/><Metric label="Go to market" value={profile.go_to_market} tone="emerald"/></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><TrendingUp size={18} className="text-amber-600"/> Strategy shifts</h3>{shifts.length? <div className="mt-4 space-y-3">{shifts.map((s,i)=><div key={i} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-bold text-slate-900">{s.from_strategy} <span className="text-amber-600">→</span> {s.to_strategy}</p><p className="mt-1 text-sm text-slate-600">Confidence {(s.confidence*100).toFixed(0)}%</p><div className="mt-3 flex flex-wrap gap-2">{s.signals.map(x=><span key={x} className="rounded-full bg-white px-2.5 py-1 text-xs font-medium text-amber-800">{x}</span>)}</div></div>)}</div>:<p className="mt-4 text-sm text-slate-500">No high confidence shift detected in the current history.</p>}</div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><Flag size={18} className="text-blue-600"/> First signal</h3>{first?<div className="mt-4 rounded-xl bg-blue-50 p-4"><p className="font-bold text-slate-900">{first.title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{first.description}</p><p className="mt-3 text-xs font-semibold text-blue-700">{new Date(first.date).toLocaleDateString()}</p></div>:<p className="mt-4 text-sm text-slate-500">No clear first signal found.</p>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><Lightbulb size={18} className="text-violet-600"/> Recurring patterns</h3>{patterns.length?<div className="mt-4 grid gap-3 md:grid-cols-2">{patterns.slice(0,6).map(p=><div key={p.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-semibold text-slate-900">{p.name}</p><p className="mt-1 text-sm text-slate-600">{p.description}</p><div className="mt-3 flex flex-wrap gap-2">{p.sequence.map(x=><span key={x} className="rounded-full bg-white px-2 py-1 text-xs text-slate-600">{x.replaceAll('_',' ')}</span>)}</div></div>)}</div>:<p className="mt-4 text-sm text-slate-500">No recurring pattern met the current threshold.</p>}</section>
  </div>
}
function Metric({label,value,tone}:{label:string,value:string,tone:string}){const bg:any={blue:'bg-blue-50 text-blue-700',violet:'bg-violet-50 text-violet-700',cyan:'bg-cyan-50 text-cyan-700',emerald:'bg-emerald-50 text-emerald-700'};return <div className={`rounded-xl p-4 ${bg[tone]}`}><p className="text-xs font-bold uppercase tracking-wide opacity-80">{label}</p><p className="mt-2 text-lg font-bold capitalize text-slate-900">{value}</p></div>}
function Loading(){return <div className="rounded-2xl border border-slate-200 bg-white p-12 text-center"><div className="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-slate-200 border-t-blue-600"/><p className="mt-4 text-slate-600">Analyzing strategy and historical patterns…</p></div>}; function Empty(){return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-slate-500">No strategy data available.</div>}
