import React, { useEffect, useMemo, useState } from 'react'
import { CalendarClock, History, Sparkles } from 'lucide-react'
import { api } from '../services/api'

export default function TimeMachine({ competitor }: { competitor: string }) {
  const [date,setDate]=useState(''); const [known,setKnown]=useState<any[]>([]); const [later,setLater]=useState<any[]>([]); const [loading,setLoading]=useState(false)
  const suggested=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-90);return d.toISOString().slice(0,10)},[])
  useEffect(()=>{if(!date)setDate(suggested)},[suggested,date])
  async function travel(){setLoading(true);try{const r=await api.timeMachine(competitor,date,true);setKnown(r.known_at_time?.events||[]);setLater(r.happened_later?.events||[])}catch(e){console.error(e)}finally{setLoading(false)}}
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600"><CalendarClock size={22}/></span><div><h2 className="text-xl font-bold text-slate-900">Market Time Machine</h2><p className="text-sm text-slate-500">Jump back in time and separate what was known then from what happened afterward.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-slate-300 px-4 py-3"/><button onClick={travel} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white hover:bg-indigo-700">Travel back</button></div></section>{loading?<div className="rounded-2xl bg-white p-10 text-center text-slate-500">Reconstructing the historical state…</div>:date&&<div className="grid gap-6 lg:grid-cols-2"><Column title={`Known on ${new Date(date).toLocaleDateString()}`} icon={<History size={18}/>} items={known} tone="blue"/><Column title="What happened afterward" icon={<Sparkles size={18}/>} items={later} tone="violet"/></div>}</div>
}
function Column({title,icon,items,tone}:{title:string,icon:React.ReactNode,items:any[],tone:'blue'|'violet'}){return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className={`flex items-center gap-2 font-bold ${tone==='blue'?'text-blue-700':'text-violet-700'}`}>{icon}{title}</h3><div className="mt-4 space-y-3">{items.length?items.map((e,i)=><div key={i} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold text-slate-900">{e.title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{e.description}</p><p className="mt-2 text-xs text-slate-400">{new Date(e.date).toLocaleDateString()}</p></div>):<p className="text-sm text-slate-500">No events in this window.</p>}</div></section>}
